### ISSUE TITLE
PoW Dynamic Difficulty

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-chain#247]
As a miner, I want PoW difficulty to dynamically adjust to the observed hash rate.

- [ ] Update PoW Mining contract to record block rate
- [ ] Update PoW Mining contract to change difficulty every N blocks based on observed block rate
- [ ] Update PoW Mining contract to provide interface to get the current difficulty 
   - The contract needs to support multiple entry points. One of which is the syscall override, the other is a normal contract entry point.
   - The entry points need to check privileges differently. `verify_block_sig` **must** be called from a system context, but `get_difficulty` can be called from anywhere, including an API.
- [ ] Update Block Producer plugin to mine based on current difficulty

**Comment by sgerbino** [comment]
We believe this to be resolved.
