### ISSUE TITLE
`db_*_object` requires contract address

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-chain#390]
Compiled smart contracts can be uploaded to any address. The existing `db_*_object` calls require knowing the address of the contract.

There are a couple of ways we could solve this:

- Add separate db methods that grab the contract address from the apply context. System contracts may still want to specify system address spaces manually, but user smart contracts will only ever have access to their address space.

- Add a new system call, `get_contract_address` that returns the current contract address so the contract can call db methods with the correct contract address.

I lean towards the first solution because it creates a simpler interface for smart contracts and bypasses an additional context swap of getting the contract address.

**Comment by theoreticalbts** [comment]
### Current state of the code

Currently, the contract address space check is implemented with four lines copy-pasted into each of the `db_*_object()` functions, for `put_object()` see [here](https://github.com/koinos/koinos-chain/blob/af89e99bf961b44cd89ab002cd0572177256532b/libraries/chain/system_calls.cpp#L414-L418).

The intended definition of `space` is noted in a comment [here](https://github.com/koinos/koinos-chain/blob/af89e99bf961b44cd89ab002cd0572177256532b/libraries/statedb/include/koinos/statedb/statedb.hpp#L260-L269) at the bottom of `statedb.hpp`.

Currently the code implements an assumption of one space per contract.  However, the spec in `statedb.hpp` suggests that the `space` field should be divided into bits, so the following checks are performed:

- (a) The high-order 160 bits must match the contract ID.
- (b) The middle 72 bits must be zero.
- (c) The low-order 24 bits can be anything (application-defined).

The current equality check sort-of enforces (a) and (b) but not (c), and it has a different ordering of the bits from this specification.  The idea is that (b) can be used to implement different semantics, the meaning of non-zero values for these bits can be defined for particular features.  (Right now we are already thinking pretty seriously about implementing a feature that would use one of these bits.)

### My proposal

First, let's name these fields:

- (a) Let's call the 160-bit field `contract_id`.
- (b) Let's call the 72-bit field `table_flags`, divided into 8 low bits `table_lflags` and 64 high bits `table_hflags`
- (c) Let's call the 24-bit field `table_id`.

I propose the following spec:

- System calls no longer take an argument of `space`.  In its place are the two arguments: `uint64_t table_hflags` and `uint32_t table_id`.
- The highest 8 bits of the `table_id` argument are actually `table_lflags`, but none of these flags are defined, so we force them to be zero.
- When defining flags, we should prefer `table_hflags` unless there is a compelling reason to use `table_lflags`.
- Designate one bit of `table_hflags` as `SYS_TABLE_FLAG`.  This bit is set to `1` if the contract is trying to access a system table.
- If `SYS_TABLE_FLAG` bit is clear, fill in the `contract_id` with `get_caller()`.
- If `SYS_TABLE_FLAG` bit is set, check privilege, then fill in `contract_id` with the special value `SYS_TABLE`.
- The low 24 bits of `table_id` cannot all be zero (this has some reserved meaning, the first table is `1`).

We can then reorganize the code as follows to be spec-compliant:

- Decide once and for all on the bit ordering of the fields
- Implement `db_*_object()` methods to follow the spec
- Update the comment in `statedb.hpp`
- Define `SYS_TABLE` in `constants.hpp`
- Redefine the three system tables in `constants.hpp` to be `table_id` values.

### Table ID purpose

The intent of `table_id` is that eventually some of the CDT tooling will be able to automagically generate a different `table_id` value here for each object type, and put the serialization spec somewhere standard (possibly on-chain).  This makes it possible to build tooling to automagically deserialize any object in the state [1].

[1] This is limited to smart contracts that are compliant (i.e. the smart contract was built with our CDT and/or follows the relevant specs).  No attempt will be made to *enforce* this compliance -- so nothing prevents a user from uploading a smart contract that doesn't include a serialization spec, or puts objects that don't comply with the serialization spec.  Of course any generic deserialization tooling will have to deal with contracts and objects created by an attacker Eve, so it will need to handle situations where the object doesn't auto-deserialize as expected.

### Bit ordering

As far as the reasoning of bit ordering, putting `contract_id` in the high bits ensures that a contract's storage is contiguous in key space.  The main benefit of this is it will be simple to write (native) code to dump all of the objects for a particular contract, which may be quite useful for various purposes (debugging, analytics, snapshots of token balances...).
