### ISSUE TITLE
PoW verify_block_signature causes side effects

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-chain#408]
The PoW `verify_block_signature` override causes side effects both in the pow metadata object and block producer balances.

The call to `verify_block_signature` implies that it should not have side effects because of the `check_block_signtature` option to `apply_block`.

There are two solutions to the problem:

- Rearchitect our system calls to have a read-only verification and write system call. Then require `verify_block_signature` is read only and update the PoW contract to follow the new arcitecture.
- Remove `check_block_signature` flag and allow `verify_block_signature` to have side effects.

**Comment by sgerbino** [comment]
For now, we will remove the `check_block_signature` flag and rename the system call to indicate it does more than verification.
