### ISSUE TITLE
Implement the capsule library

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-chain#423]
As a smart contract developer, I would like a way to indicate the data I wish to store is transient for additional cost savings.

- [ ] Add `pre_block`/`post_block`/`pre_transaction`/`post_transaction` system calls.
  - `post_block` thunk implementation is the capsule creation logic
- [ ] Add value wrapper message in proto containing bool and bytes fields
- [ ] Create an exception `pagefault` that contains JSON metadata indicating the `object_space` and `object_key` of the paged out object
- [ ] State DB Updates:
    - Implement `state_db::page_out`
    - Implement `state_db::page_in`
    - Modify `get_object`/`put_object`/`remove_object` that throws `pagefault` exception containing the necessary data
- [ ] Add `page_out` system call/thunk
- [ ] Add `page_in` system call/thunk
- [ ] Extend the Koinos resource subsystem (C++) to support byte days for State Rent
- [ ] Extend the Koinos resource system contract to support byte days for State Rent
- [ ] Add a flag to `put_object` to denote a permanent vs transient object and the number of state rent days
- [ ] Extend `put_object` to allow the storage of both permanent and transient objects and charge resources appropriately
- [ ] Extend `put_object` to track eviction times

**Comment by mvandeberg** [comment]
This is a defunct feature proposal. If it is integrated in to Koinos in the future, planning it will start from scratch.
