### ISSUE TITLE
Allow user-specifiable resource limits for read_contract

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-chain#435]
As a node operator, I want to configure the resource limits my node will impose on smart contract queries via `read_contract()`.

As a client querying `read_contract()`, I want the ability to request the node to enforce resource limits.

- Read requests can optionally specify resource limits for reading a smart contract.
- The node config file can optionally specify resource limits for reading smart contracts.

"Optionally" means of course it might not be specified, if that happens:

- If the node config file doesn't specify a limit, then a reasonable default limit is used instead.
- If the read request doesn't specify a limit, then it inherits from the node config.

Also there is the case the two limits are both specified:

- If the read request wants less than or equal to the value specified in the node config, apply the smaller limit.
- If the read request wants more than the value specified in the node config, fail the request immediately without even attempting to execute it.

**Comment by sgerbino** [comment]
See option `READ_COMPUTE_BANDWIDTH_LIMIT`.
