### ISSUE TITLE
Edge case testing of call depth limit and tick limit

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-chain#456]
Currently we don't have any testing of call depth limit, and tick limit is only tested by a do-forever loop that doesn't aim for any specific number of ticks.

We should implement edge case testing:

- Verify a contract that recurses to n-1 calls succeeds
- Verify a contract that recurses to n calls fails

- Run a loop k times, then add n-1 no-ops and check success
- Run the same loop k times, but add n no-ops and check failure

We will probably need to manually construct wasm for these test cases.

**Comment by mvandeberg** [comment]
Handled by koinos/koinos-integration-tests#38
