### ISSUE TITLE
Audit maximum call depth

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-chain#460]
Currently, the maximum call depth is a compile time parameter encoded in each backend.

We may want an interface that allows users of `vmmanager` to configure the call depth.  There are some issues to keep in mind here:

- For contracts that are executed on-chain, changing the call depth limit is a change to consensus.  Everyone must change their call depth limit simultaneously, to avoid situations where Alice and Bob disagree whether some transaction T is illegal (if T uses more than Alice's call depth limit, but less than Bob's).
- For read-only calls that don't occur on the blockchain, call depth can be set to anything.
- We need to analyze the source code and perhaps experiment to determine what are the consequences of setting max call depth too large.  Can we get into situations where we SIGSEGV due to exceeding the native C++ stack if we have the maximum number of recursive system calls each going just below the depth that would cause termination?

**Comment by sgerbino** [comment]
This is handled, see the failure integration tests.
