### ISSUE TITLE
Audit smart contract memory usage

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-chain#461]
The maximum the VM allows a smart contract to allocate is currently set to `memory_pages_limit = 512`.  This should be settable.

As with the call depth limit mentioned in #460, changes need to happen simultaneously for everyone in consensus (i.e. setting it is part of governance).

Except for non-consensus read-only calls, you should be able to set any desired memory limit, up to some threshold set by the node operator.

**Comment by sgerbino** [comment]
These were added to `failures` integration tests.
