### ISSUE TITLE
Add means to select VM via config / CLI and in unit tests

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-chain#463]
We can toggle between multiple `vm_backend` implementations, but currently EOS-VM is slated to be removed, which will leave us with only the Fizzy backend.

Toggling between various VM backends is done via environment variable, but according to [this comment](https://github.com/koinos/koinos-chain/pull/458#discussion_r682903894), using environment variable for this purpose is unacceptable, and the code will be removed with EOS-VM in #459.

If we ever support an additional VM in the future, we will need some means to switch between them.  We will need options for switching in the config / CLI, and we will also need to specify how to select a VM for running the unit tests (or make alternative arrangements, e.g. perhaps set up the tests to always run against all VM's).

**Comment by sgerbino** [comment]
We're only going to have one VM.
