### ISSUE TITLE
Document system calls that should not be overridden

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-chain#485]
~~While working on #483, I realized a potential problem with certain system calls. I/O based system calls need to be aware of overrides, or else an override would permanently break the system call (`get_caller` for example). We should extract the part of #483 that implemented this as its own PR.~~

Edit: We should research and document any and all system calls that cannot be overridden and would result in bricking the chain. The artifact of this task should be a new page added to http://docs.koinos.io that explains which systems calls and a blurb of why.

**Comment by sgerbino** [comment]
We should research and document any and all system calls that cannot be overridden and would result in bricking the chain. The artifact of this task should be a new page added to http://docs.koinos.io that explains which systems calls and a blurb of why.
