### ISSUE TITLE
[FEATURE]: add a system call to retrieve the address of the account who signed the transaction calling the contract

### ISSUE THREAD

**Issue by harpagon210** [koinos/koinos-chain#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

As a smart contract developer I want to be able to retrieve the address of the account that signed the transaction calling the smart contract, this would allow me to:

- allow/block execution of functions based on whitelisted/blacklisted accounts (i.e: memberships)
- use the address as a key for object storage/retrieval (i.e: user profiles)

Right now, a workaround to get the address of the transaction signer is by adding an address argument that the user populates with his own address and then perform a `system::require_authority` on that address (to check ownership)

**Comment by joticajulian** [comment]
You can use `system_call::recover_public_key`. With the public key you can use koinos libraries tools to get the address using `to_address_bytes()`. Example:
```
auto addr = util::converter::to< crypto::public_key >( system_call::recover_public_key( context, ecdsa_secp256k1, sig, trx.id() ) ).to_address_bytes();
```
For Assembly Script we still need a function convert the public key to address.

**Comment by mvandeberg** [comment]
In v0.3.0 there is a payer field in the transaction header, accessible via `get_transaction_field`. Other signatures are available via the same API, but to get an address, will need to be computed in the contract via `recover_public_key`. However, this is not a recommended pattern as the signatures are intentionally opaque to allow for different signature algorithms in the future.

The better pattern is to have the address in question be a parameter to the contract call and then ask that address if they authorize the contract call.
