### ISSUE TITLE
Information about who mined/produced a block

### ISSUE THREAD

**Issue by bgornicki** [koinos/koinos-chain#539]
There should be a way to tell who mined/produced a block.

**Comment by joticajulian** [comment]
in **koinos V2** you can get the signer from the active data in the block
https://github.com/koinos/koinos-proto/blob/v0.2.0/koinos/protocol/protocol.proto#L59
```
message active_block_data {
   bytes transaction_merkle_root = 1;
   bytes passive_data_merkle_root = 2;
   bytes signer = 3;
}
```

In **koinos v3** you have the signer in the headers
https://github.com/koinos/koinos-proto/blob/master/koinos/protocol/protocol.proto
```
message block_header {
   bytes previous = 1 [(btype) = BLOCK_ID];
   uint64 height = 2 [jstype = JS_STRING];
   uint64 timestamp = 3 [jstype = JS_STRING];
   bytes previous_state_merkle_root = 4;
   bytes transaction_merkle_root = 5;
   bytes signer = 6;
}
```
