### ISSUE TITLE
[BUG]: "get_block" and "get_block_field" return "block does not exist" [v3]

### ISSUE THREAD

**Issue by roaminroe** [koinos/koinos-chain#612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Both system calls "get_block" and "get_block_field" return "block does not exist"

### Expected behavior

"get_block" should return the block being processed
"get_block_field" should return the requested field of the block being processed

### Steps to reproduce

With any Koinos CDT/SDK, write a contract that calls the "get_block" or the "get_block_field" system calls.

```ts
// with the AS SDK v3
const b = System.getBlock();
// or
const f = System.getBlockField('header.signer');
```
Wasm of a compiled contract that calls "get_block" [contract.wasm.zip](https://github.com/koinos/koinos-chain/files/8127238/contract.wasm.zip)

### Environment

```markdown
- OS: Docker
```

**Comment by sgerbino** [comment]
Resolved by #618.
