### ISSUE TITLE
[FEATURE]: protection against scams in `check_authority`

### ISSUE THREAD

**Issue by joticajulian** [koinos/koinos-chain#710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

Let's say there is a scam contract giving you an airdrop or something, and you sign the transaction.
This scam contract could request a transfer of koins. If the user has not overridden the authorize function then `check_authority` will check the signatures. As the signature of the user is valid then the transfer will be authorized and the koins will be stolen.

Current implementation:

https://github.com/koinos/koinos-chain/blob/5abb3e8658e986cc317bb2b1dab9138aedd9fb87/libraries/chain/system_calls.cpp#L1374-L1385

My suggestion is to add an extra requirement when checking signatures: The caller of `check_authority` must be the contract id of `get_operation`. In this sense the user is more confident when signing transactions and can experiment with more contracts in the ecosystem without the fear of being stolen.

(In the case of the authorize function there is no need to add this extra check because this can be addressed with #675)

**Comment by mvandeberg** [comment]
But what about a DEX contract?

Typically, they are implemented by having their own entry point that will in turn call `koin.transfer`, which is the "scam" that you've described. By making this change, we risk crippling the capabilities of many potential legitimate projects.

IMO, you shouldn't sign anything you don't trust. And if you want to play around with less than trustworthy contracts, you should be using an account that is properly protected and has minimal KOIN available to it.

**Comment by joticajulian** [comment]
The UI of the DEX could create a transaction with 2 operations: one making a transfer to the DEX, and a second one that triggers the entry point of the DEX. The contract of the DEX can read both operations to see the amount transferred. Then the DEX can operate with this amount and give a return if needed.

In this case the user can see in the screen what is the maximum amount of tokens he is putting in risk.

If something goes wrong the DEX can reject the operation and the whole transaction will be rejected including the transfer.

**Comment by mvandeberg** [comment]
> The UI of the DEX could create a transaction with 2 operations: one making a transfer to the DEX, and a second one that triggers the entry point of the DEX. The contract of the DEX can read both operations to see the amount transferred. Then the DEX can operate with this amount and give a return if needed.
> 
> In this case the user can see in the screen what is the maximum amount of tokens he is putting in risk.
> 
> If something goes wrong the DEX can reject the operation and the whole transaction will be rejected including the transfer.

This doesn't actually solve the "problem", other than making the transfer of the token explicit to the user. The DEX can still just allow the operation to succeed, not reverting the transaction, and stealing the user's tokens.

It also encourages bad design by requiring a transaction to inspect other operations within a transaction. While allowed via system calls, it should be viewed as a sign of poor design to have to break an abstraction layer.

The behavior you desire can be implemented entirely with current `authorize` overrides. In your wallet contract, you can get the current operation and check the caller of the authorize function against the operation, disallowing if they do not match. Then, to allow such authorization on a per transaction basis, you can have an entry point in the wallet that gets the current transaction id, stores it, and when `authorize` is called, authorizes the call if the current transaction's id matches.

After discussing this issue, we do not want to make changes to the framework to lock users in to a specific security model. That is the point of wallet contracts. However, we feel that allowing submission of a transaction without broadcasting provides an opportunity for the user to inspect the transaction receipt, specifically transfer events, and send once they are comfortable with the result of the transaction. This does not protect from every scenario, but it is a simple change that adds significant security.

If you're satisfied with this answer, please close the issue.

**Comment by joticajulian** [comment]
Thanks I agree with the solution.
In the case of contract wallets I was planning to use the solution proposed in #675. This issue was more for the users that don't want to upload a contract and override the authorize function. The proposal you suggest is a good solution, we could add in the UI something like "Test Contract" and then check the results in the events 👍 

I'm closing this ticket.
