### ISSUE TITLE
[BUG]: Assertion failed on `module exited due to trap`

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-chain#720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When submitting a transaction that calls a wasm module that exits due to a trap, the exception is not correctly wrapped and results in an assertion failing.

### Expected behavior

Lower level exceptions should be correctly caught, wrapped, and re-thrown.

### Environment

```markdown
- OS: MacOS
```

**Comment by sgerbino** [comment]
Resolved by #737.
