### ISSUE TITLE
[BUG]: Particular hash algorithms are not enforced

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-chain#751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently, the code is written in such a way that any of the supported multihash identifiers can be used anywhere a hash or public key is required.  So in any of the places the blockchain looks for a hash -- block ID's, transaction ID's, addresses, etc. -- Alice could use a sha2-256, Bob could use a ripemd160, Charlie could use a sha2-512, Dan could use Keccak...and they'd all happily exist on the same chain.

### Expected behavior

Every place that consensus expects a hash, (or public key, or signature), it should check that it's a particular type of hash.  E.g. we might enforce that block ID's and transaction ID's must be sha256's, while addresses must all be RIPEMD160's.

### Environment

```markdown
- OS: All
```

### Anything else?

The main benefit of using multihashes is *not* to support multiple hashes simultaneously.  For each place a hash can go, consensus should always enforce the use of only one single legitimate hash algorithm.

"Block ID's are always sha256's" is an invariant that's expected to be enforced by consensus for years.

The purpose of the multihash is to reserve space in on-chain objects and RPC serializations, to future-proof in case the original consensus enforced One True Hash Algorithm is ever broken and needs to be switched out for something else (e.g. avoid what's happening now with Git and sha1).

Ideally the invariant would be enforced forever, but nobody's yet invented a hash algorithm that will provably remain secure forever, regardless of advances in cryptanalysis and computing power.

Let's examine that scenario more closely:  What if someday in the distant future sha256 starts to look like it might be about to be broken, and we want to upgrade it to some algorithm that doesn't exist yet, say sha4?

Then here's how to do it (required governance actions omitted for simplicity):

- (1) Implement new native C++ thunk for `hash()` to compute sha4, and `apply_block()` to enforce sha4 block ID's
- (2) Release the upgrade as a hardfork for block producers
- (3) When sufficient block producers have upgraded, do an in-band update to point the system calls to the new thunks
- (4) Since the new `hash()` thunk and old `hash()` thunk do the same thing on the now-immutable pre-update chain history, the old thunk can now be replaced with an implementation that simply calls the new thunk
- (5) We have to keep both pre- and post- versions of `apply_block()` around.  (We may be tempted to merge them into a single implementation with a feature flag, but experience has shown unsustainable feature flag growth leads to a very cluttered, hard-to-read codebase.  It's better to have the "live" version of the function be a straightforward implementation for only the latest and greatest hardfork; old versions that are still needed to properly process historical blocks can be moved out of the way in a separate directory.)

**Comment by mvandeberg** [comment]
The hash algorithm used for block ids is set in the genesis data and can be upgraded once the chain is live.

The current genesis hash is sha256. If we want to update the hash algorithm in the future, we have to do a hardfork to add the new algorithm and then a governance upgrade to change the block id algorithm.

**Comment by theoreticalbts** [comment]
I checked into this and it seems to be ok to close.

I verified the following all seem to be enforced to be the same as `context.block_hash_code()`.:

- Blocks
- Transactions
- Transaction Merkle roots
- Operation Merkle roots
- Transaction ID in transaction

Exceptions are the following:

- `bytes` values marked as `CONTRACT_ID` or `ADDRESS`
- `chain_id` (is checked for equality with hard-coded constant anyway)
- `transaction.id` (should be enforced via Merkle)
- `block_receipt.state_merkle_root` (is output)
- `previous` (enforced by check)
- `previous_state_merkle_root` (but see #759)
- `approved_proposals` (should be enforced to be a txid that was previously accepted)
