### ISSUE TITLE
[QUESTION]: Full JavaScript/TypeScript support via QuickJS.

### ISSUE THREAD

**Issue by artem-v-shamsutdinov** [koinos/koinos-chain#783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the documentation?

- [X] I have read the documentation

### Ask a question

[QuickJS](https://bellard.org/quickjs/) is a fast and small JavaScript engine that [compiles to WASM](https://github.com/jeasonstudio/quickjs.wasm).  Would it be possible to add full JavaScript/TypeScript support to Koinos via such a solution?

**Comment by artem-v-shamsutdinov** [comment]
IMHO enabling full TypeScript support will open the door to the vast majority of JS/TS developers.

**Comment by mvandeberg** [comment]
We already have AssemblyScript support, which is based on TS. It is easy to begin using AS if you already know TS. Please see https://github.com/koinos/koinos-sdk-as. AS also appears to be a more popular technology based on GitHub statistics.
