### ISSUE TITLE
[BUG]: Could not create state node

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-chain#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Occasionally chain will log that it could not create new state node.

While working on p2p, I found that this message was being logged when a child block was attempting to be applied while the parent block is being applied. This leads to a race condition that can result in timeouts within p2p. The race condition is not good in chain either.

When the parent block is being finalized, we release all locks and request a unique lock in order to bump head block, fork heads, and LIB atomically. When creating a new state node, state db waits for the parent node to be finalized, holding a lock while it does. Thankfully, creating a state node does use an internal timeout otherwise this would result in a complete deadlock of the node.

### Expected behavior

We should detect this condition and return a meaningful error. I suggest `unknown_previous_block` for two reasons.

1. p2p is already handling this error and will attempt to re-apply the block when the parent is applied.
2. Internal to chain, this creates a consistent definition for the error. We only know of a block once it has been successfully applied. The error in this case makes sense because the parent node has not yet finished applying, therefore the previous block is unknown.

### Environment

```markdown
- OS:
```

**Comment by solthereum** [comment]
Hi,	@mvandeberg , sorry for leaving comment here without your agreement and respecting the team rule. Because I wanna contribute to koinos team's development and join your team, so I am going to solve issues. So could you give me some issue to be solved quickly as test task?

**Comment by sgerbino** [comment]
> Hi, @mvandeberg , sorry for leaving comment here without your agreement and respecting the team rule. Because I wanna contribute to koinos team's development and join your team, so I am going to solve issues. So could you give me some issue to be solved quickly as test task?

This is a good beginner task: https://github.com/koinos/koinos-chain/issues/676
It involves defining a new protobuf message in https://github.com/koinos/koinos-proto
Reach out to me, @sgerbino, or @mvandeberg on Telegram in #Developers.

**Comment by solthereum** [comment]
sure, I will do it
